package TestMikeDataStruct

import MikeDataStruct.MikeMutableLinkedList
import org.scalatest.FunSuite

class MikeMutableLinkedListTest extends FunSuite {
  test("Can peek, push, pop, peekLast, pushLast, and popLast. Can keep track length along the way and check if value is present") {
    val l = new MikeMutableLinkedList[Int]
    assert(l.length === 0)
    assert(l.peek === None)
    assert(l.peekLast === None)
    assert(l.contains(0) === false)
    assert(l.contains(1) === false)
    assert(l.contains(2) === false)
    assert(l.contains(1000) === false)

    l.pop
    assert(l.length === 0)
    assert(l.peek === None)
    assert(l.peekLast === None)
    assert(l.contains(0) === false)
    assert(l.contains(1) === false)
    assert(l.contains(2) === false)
    assert(l.contains(1000) === false)

    l.popLast
    assert(l.length === 0)
    assert(l.peek === None)
    assert(l.peekLast === None)
    assert(l.contains(0) === false)
    assert(l.contains(1) === false)
    assert(l.contains(2) === false)
    assert(l.contains(1000) === false)

    l.push(1)
    assert(l.peek === Some(1))
    assert(l.peekLast === Some(1))
    assert(l.length === 1)
    assert(l.toString === "1")
    assert(l.contains(0) === false)
    assert(l.contains(1) === true)
    assert(l.contains(2) === false)
    assert(l.contains(1000) === false)

    l.push(2)
    assert(l.peek === Some(2))
    assert(l.peekLast === Some(1))
    assert(l.length === 2)
    assert(l.toString === "2 -> 1")
    assert(l.contains(0) === false)
    assert(l.contains(1) === true)
    assert(l.contains(2) === true)
    assert(l.contains(1000) === false)

    l.push(3)
    assert(l.peek === Some(3))
    assert(l.peekLast === Some(1))
    assert(l.length === 3)
    assert(l.toString === "3 -> 2 -> 1")
    assert(l.contains(0) === false)
    assert(l.contains(1) === true)
    assert(l.contains(2) === true)
    assert(l.contains(1000) === false)

    l.push(4)
    assert(l.peek === Some(4))
    assert(l.peekLast === Some(1))
    assert(l.length === 4)
    assert(l.toString === "4 -> 3 -> 2 -> 1")
    assert(l.contains(0) === false)
    assert(l.contains(1) === true)
    assert(l.contains(2) === true)
    assert(l.contains(1000) === false)

    l.pushLast(0)
    assert(l.peek === Some(4))
    assert(l.peekLast === Some(0))
    assert(l.length === 5)
    assert(l.toString === "4 -> 3 -> 2 -> 1 -> 0")
    assert(l.contains(0) === true)
    assert(l.contains(1) === true)
    assert(l.contains(2) === true)
    assert(l.contains(1000) === false)

    l.pushLast(-1)
    assert(l.peek === Some(4))
    assert(l.peekLast === Some(-1))
    assert(l.length === 6)
    assert(l.toString === "4 -> 3 -> 2 -> 1 -> 0 -> -1")
    assert(l.contains(0) === true)
    assert(l.contains(1) === true)
    assert(l.contains(2) === true)
    assert(l.contains(1000) === false)

    assert(l.pop === Some(4))
    assert(l.peek === Some(3))
    assert(l.peekLast === Some(-1))
    assert(l.length === 5)
    assert(l.toString === "3 -> 2 -> 1 -> 0 -> -1")
    assert(l.contains(0) === true)
    assert(l.contains(1) === true)
    assert(l.contains(2) === true)
    assert(l.contains(1000) === false)

    assert(l.pop === Some(3))
    assert(l.peek === Some(2))
    assert(l.peekLast === Some(-1))
    assert(l.length === 4)
    assert(l.toString === "2 -> 1 -> 0 -> -1")
    assert(l.contains(0) === true)
    assert(l.contains(1) === true)
    assert(l.contains(2) === true)
    assert(l.contains(1000) === false)

    assert(l.popLast === Some(-1))
    assert(l.peek === Some(2))
    assert(l.peekLast === Some(0))
    assert(l.length === 3)
    assert(l.toString === "2 -> 1 -> 0")
    assert(l.contains(0) === true)
    assert(l.contains(1) === true)
    assert(l.contains(2) === true)
    assert(l.contains(1000) === false)

    assert(l.popLast === Some(0))
    assert(l.peek === Some(2))
    assert(l.peekLast === Some(1))
    assert(l.length === 2)
    assert(l.toString === "2 -> 1")
    assert(l.contains(0) === false)
    assert(l.contains(1) === true)
    assert(l.contains(2) === true)
    assert(l.contains(1000) === false)

    l.pushLast(0)
    assert(l.peek === Some(2))
    assert(l.peekLast === Some(0))
    assert(l.length === 3)
    assert(l.toString === "2 -> 1 -> 0")
    assert(l.contains(0) === true)
    assert(l.contains(1) === true)
    assert(l.contains(2) === true)
    assert(l.contains(1000) === false)

    assert(l.popLast === Some(0))
    assert(l.peek === Some(2))
    assert(l.peekLast === Some(1))
    assert(l.length === 2)
    assert(l.toString === "2 -> 1")
    assert(l.contains(0) === false)
    assert(l.contains(1) === true)
    assert(l.contains(2) === true)
    assert(l.contains(1000) === false)

    assert(l.popLast === Some(1))
    assert(l.peek === Some(2))
    assert(l.peekLast === Some(2))
    assert(l.length === 1)
    assert(l.toString === "2")
    assert(l.contains(0) === false)
    assert(l.contains(1) === false)
    assert(l.contains(2) === true)
    assert(l.contains(1000) === false)

    assert(l.popLast === Some(2))
    assert(l.peek === None)
    assert(l.peekLast === None)
    assert(l.length === 0)
    assert(l.toString === "")
    assert(l.contains(0) === false)
    assert(l.contains(1) === false)
    assert(l.contains(2) === false)
    assert(l.contains(1000) === false)

    l.push(1)
    assert(l.peek === Some(1))
    assert(l.peekLast === Some(1))
    assert(l.length === 1)
    assert(l.toString === "1")
    assert(l.contains(0) === false)
    assert(l.contains(1) === true)
    assert(l.contains(2) === false)
    assert(l.contains(1000) === false)

    assert(l.pop === Some(1))
    assert(l.peek === None)
    assert(l.peekLast === None)
    assert(l.length === 0)
    assert(l.toString === "")
    assert(l.contains(0) === false)
    assert(l.contains(1) === false)
    assert(l.contains(2) === false)
    assert(l.contains(1000) === false)

    l.push(1)
    assert(l.peek === Some(1))
    assert(l.peekLast === Some(1))
    assert(l.length === 1)
    assert(l.toString === "1")
    assert(l.contains(0) === false)
    assert(l.contains(1) === true)
    assert(l.contains(2) === false)
    assert(l.contains(1000) === false)

    assert(l.popLast === Some(1))
    assert(l.peek === None)
    assert(l.peekLast === None)
    assert(l.length === 0)
    assert(l.toString === "")
    assert(l.contains(0) === false)
    assert(l.contains(1) === false)
    assert(l.contains(2) === false)
    assert(l.contains(1000) === false)
  }
}
